### ISSUE TITLE
Remove calls to http://vistaservice.utah.gov/Residence/GetResidencesInfoFromQueries/

### ISSUE THREAD

**Issue by stdavis** [agrc/vista#2]
This shouldn't be needed since we have a direct connection to their database now. Only question that I have is how to deal with the `query` parameter which I believe is used to limit the number of points returned. Maybe we can just display all points with a scale dependency?

**Comment by brigsz** [comment]
Is it safe to assume that we only use this call in one place in the vista app?  Do we use it in other spots?

**Comment by stdavis** [comment]
Yes, that's safe to assume. I don't think that we use this in other spots.

**Comment by stdavis** [comment]
This is no longer valid. We couldn't make a direct connection to their database work. So DJ built us a new service on services-vista.utah.gov.
