### ISSUE TITLE
New Dev DNS

### ISSUE THREAD

**Issue by stdavis** [agrc/vista#25]
`vista-map.dev.utah.gov`

@steveoh Would you mind wiring it up to the firebase project and posting the DNS records for @nathankota?

**Comment by steveoh** [comment]
I don't have the keys to do this any longer. @nathankota will have to add this part to the ticket also. The project id is `ut-dts-agrc-vista-dev`

**Comment by nathankota** [comment]
INC1496035

**Comment by nathankota** [comment]
Service Now incident is resolved. I do not have repo privileges to close this github issue.

**Comment by steveoh** [comment]
Where did you get the ip's from in that incident? The DNS has not been added to the firebase project.

**Comment by nathankota** [comment]
I used the same ip's as all the other recent DNS requests. If that was not correct I will do what I need to to get it resolved.

**Comment by steveoh** [comment]
I didn't realize they were all the same until now.

**Comment by nathankota** [comment]
INC1496503

**Comment by nathankota** [comment]
INC1496503 is resolved. I do not have the credentials to close this issue/task.

**Comment by steveoh** [comment]
access updated
