### ISSUE TITLE
New Production DNS

### ISSUE THREAD

**Issue by stdavis** [agrc/vista#26]
@nathankota please...
- [x] ask to have the cloud machine assign it to `ut-dts-agrc-vista-prod`
- [ ] request this new DNS: `vista-map.ugrc.utah.gov`

**Comment by nathankota** [comment]
> @nathankota please...
> 
> * [x]  request this new DNS: `vista-map.ugrc.utah.gov` (INC1496033)
> * [ ]  ask to have the cloud machine assign it to `ut-dts-agrc-vista-prod`

**Comment by steveoh** [comment]
The correct order is to ask the cloud machine to assign it the firebase hosting project. Then you will get the ip records for the request to networking. Are all of the ip's we've been providing you in the screenshots the same? I haven't payed attention.

**Comment by nathankota** [comment]
INC1496503

**Comment by nathankota** [comment]
INC1496503 is resolved. I do not have access to this repo to close this issue/task.
