### ISSUE TITLE
Add Sanpete Address Grids Layer

### ISSUE THREAD

**Issue by stdavis** [agrc/vista#28]
Sandy Neill from Sanpete county has requested (via @gregbunce) that their county address grid layer be added to this app to help her in finding addresses in rural areas.

We met with Mark Mitchell today and he asked us to add the layer with a min scale dependency.

Layer: https://services8.arcgis.com/4HViMZMD64noZWcJ/ArcGIS/rest/services/Sanpete_Addrss_Grid/FeatureServer/1

The layer will be always on. We decided not to go down the road of adding it to a toggle button.

**Comment by gregbunce** [comment]
i placed a hard copy of the sandpete address grid in the [agrc_public_share>long_term_share>address_grids](https://drive.google.com/file/d/1-YvVPSAtGq9Z3d8RGxFMmGRYKH_FLfjs/view?usp=sharing) 

i also let Sandy Neill (Sanpete Recorder) and Wayne Larson (GIS Coordinator) know that we are using this layer in the vista web app and to let us know if they forsee any breaking changes.
