### ISSUE TITLE
Not Zooming to Precinct

### ISSUE THREAD

**Issue by stdavis** [agrc/vista#35]
From Gary...

I don't know what might have changed or how long this has been an issue, but I discovered a map issue when testing a server move last night.

Let me know if you want a ServiceNow ticket opened for this.

The issue appears to exist whether using stand alone Chrome, Firefox, or using the embedded chromium browser in VISTA.

Steps to Reproduce
Navigate in any browser to:
https://vista-map.ugrc.utah.gov/?precinctID=WJD014:00&precinct=yes&districts=no&currentX=420861.16&currentY=4497950.82&db=L&map=c&county=18

Expected Behavior
Map loads zoomed in to a reasonable rectangle containing the listed precinct.

Actual Behavior
Map loads zoomed out to show all of Utah.

I don't know if this is the issue but in Chrome there is this Console Error:
MapView.js:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'geometry')
    at MapView.js:42:33
    at w (runtime.js:62:15)
    at Generator._invoke (runtime.js:288:1)
    at Generator.t.<computed> [as next] (runtime.js:114:1)
    at r (asyncToGenerator.js:3:1)
    at s (asyncToGenerator.js:25:1)

In Firefox there is the same error, and also this one:
Identify.js:91 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at t.<anonymous> (Identify.js:91:70)
    at w (runtime.js:62:15)
    at Generator._invoke (runtime.js:288:1)
    at Generator.t.<computed> [as next] (runtime.js:114:1)
    at r (asyncToGenerator.js:3:1)
    at s (asyncToGenerator.js:25:1)

**Comment by gary-ray** [comment]
It appears that this is a data mismatch problem, and an update to the VISTAID will fix it. Zoom is working properly in other counties where the vistadb.precincts.precinct matches the value stored in VISTAID.
